var config = require('./config')

let apiConfig = {
  LOGIN : config.LOGIN,
  LOGOUT: config.LOGOUT,
  CHANGE_PWD: config.CHANGE_PWD,
  PROFILE: config.PROFILE,
  BIZ_PROFILE: config.BIZ_PROFILE,

  SYS_USER_SAVE:config.SYS_USER_SAVE,
  SYS_USER_LIST: config.SYS_USER_LIST,
  SYS_USER_DEL:config.SYS_USER_DEL,
  SYS_USER_INFO:config.SYS_USER_INFO,
  SYS_USER_EDIT:config.SYS_USER_EDIT,
  SYS_USER_BIND_ROLES:config.SYS_USER_BIND_ROLES,
  SYS_USER_ROLE_INFO:config.SYS_USER_ROLE_INFO,
  SYS_USER_RESET_PWD:config.SYS_USER_RESET_PWD,
  SYS_USER_RESET_PWD_LOIGN:config.SYS_USER_RESET_PWD_LOIGN,

  SYS_ROLE_LIST:config.SYS_ROLE_LIST,
  SYS_ROLE_INFO:config.SYS_ROLE_INFO,
  SYS_ROLE_SAVE:config.SYS_ROLE_SAVE,
  SYS_ROLE_DEL:config.SYS_ROLE_DEL,
  SYS_ROLE_MENU:config.SYS_ROLE_MENU,

  SYS_ROLE_BIND_MENU:config.SYS_ROLE_BIND_MENU,
  SYS_ROLE_MENU_BY_ID:config.SYS_ROLE_MENU_BY_ID,
  SYS_ROLE_MENU_BY_BIZID : config.SYS_ROLE_MENU_BY_BIZID,

  SYS_MENU_ALL:config.SYS_MENU_ALL,
  SYS_MENU_SAVE:config.SYS_MENU_SAVE,
  SYS_MENU_INFO:config.SYS_MENU_INFO,
  SYS_MENU_DEL:config.SYS_MENU_DEL,


  SYS_RESOURCE_LIST:config.SYS_RESOURCE_LIST,
  SYS_RESOURCE_SAVE:config.SYS_RESOURCE_SAVE,
  SYS_RESOURCE_DEL:config.SYS_RESOURCE_DEL,

  //system parameters - reference data
  SYS_PARAM_LIST:config.SYS_PARAM_LIST,
  SYS_PARAM_INFO:config.SYS_PARAM_INFO,
  SYS_PARAM_SAVE:config.SYS_PARAM_SAVE,
  SYS_PARAM_DEL:config.SYS_PARAM_DEL,
  SYS_PARAM_CATEGORY:config.SYS_PARAM_CATEGORY,


  BIZ_BASE_LIST:config.BIZ_BASE_LIST,
  BIZ_BASE_SAVE:config.BIZ_BASE_SAVE,
  BIZ_BASE_INFO:config.BIZ_BASE_INFO,
  BIZ_BASE_DEL:config.BIZ_BASE_DEL,
  BIZ_ALL_SAVE:config.BIZ_ALL_SAVE,

  ORG_LIST:config.ORG_LIST,
  ORG_SAVE:config.ORG_SAVE,
  ORG_INFO:config.ORG_INFO,
  ORG_DEL:config.ORG_DEL,

  EMPLOYEE_LIST:config.EMPLOYEE_LIST,
  EMPLOYEE_SAVE:config.EMPLOYEE_SAVE,
  EMPLOYEE_INFO:config.EMPLOYEE_INFO,
  EMPLOYEE_DEL:config.EMPLOYEE_DEL,


  ADDRESS_LIST:config.ADDRESS_LIST,
  ADDRESS_SAVE:config.ADDRESS_SAVE,
  ADDRESS_INFO:config.ADDRESS_INFO,
  ADDRESS_DEL:config.ADDRESS_DEL,

  TAG_LIST:config.TAG_LIST,
  TAG_SAVE:config.TAG_SAVE,
  TAG_INFO:config.TAG_INFO,
  TAG_DEL:config.TAG_DEL,


  BRAND_LIST:config.BRAND_LIST,
  BRAND_SAVE:config.BRAND_SAVE,
  BRAND_INFO:config.BRAND_INFO,
  BRAND_DEL:config.BRAND_DEL,
  BRAND_UPLOAD:config.BRAND_UPLOAD,
  BRAND_WITH_GROUP:config.BRAND_WITH_GROUP,


  COMMODITY_LIST:config.COMMODITY_LIST,
  COMMODITY_INFO_BY_ID:config.COMMODITY_INFO_BY_ID,
}
export default apiConfig
